name: Deploy to Firebase Hosting and Functions on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install dependencies and build the client
      - run: npm install --prefix foldspace
      - run: npm run build --prefix foldspace

      # Install dependencies for functions
      - run: npm install --prefix functions
      - run: npm install -g firebase-tools

      # Deploy both hosting and functions
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOLDSPACE_6483C }}
          projectId: foldspace-6483c
          entryPoint: .
