name: Deploy to Firebase Hosting and Functions on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install dependencies and build the client
      - run: npm install --prefix foldspace
      - run: npm run build --prefix foldspace

      # Install dependencies for functions
      - run: npm install --prefix functions

      # Deploy both hosting and functions
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FOLDSPACE_6483C }}
          channelId: live
          projectId: foldspace-6483c
          entryPoint: .

      - name: Deploy Functions
        run: firebase deploy --only functions --token ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
